# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       devLog
email:       'ghk784@naver.com'
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://choieunii.github.io/' # The base hostname & protocol for your site
twitter:     ''
github:      'https://github.com/choieunii'
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
collections:
  tags:
    output: true
    permalink: /tags/:path/
    
# Tags
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
